### ISSUE TITLE
я же могу спастить?

### ISSUE THREAD

**Issue by kisman2000** [cattyngmd/Ferret#5]
лучший клиент хочу спастить очень давно хотел катун спасибо за это

**Comment by cattyngmd** [comment]
ты не сможешь

**Comment by kisman2000** [comment]
но почему?(

**Comment by 3jq** [comment]
потому что ты пидор

**Comment by kisman2000** [comment]
а я уже спастил

**Comment by DiOnFire** [comment]
> ты не сможешь

он уже спастил

**Comment by ZenovJB** [comment]
ебало закрой щеглятина ебаная

**Comment by kisman2000** [comment]
> ебало закрой щеглятина ебаная
необязан

**Comment by DiOnFire** [comment]
чо
